name: 'testing workflow'
# Trigger on push
  push:
    branches:
      - master
jobs:
  test:
    name: posting_on_twitter
    runs-on: ubuntu-latest
    steps:
      - name: tweety
        uses: m1ner79/Github-Twittction@{VERSION}
        with:
            twitter_status: "â„ğ•–ğ•ª ğ•ªğ• ğ•¦! ğŸ‘‹ ğ•ğ•– ${{ github.event.repository.owner.name}} ğ•™ğ•’ğ•§ğ•– ğ•’ ğ•Ÿğ•–ğ•¨ ğ•”ğ• ğ•ğ•ğ•šğ•¥ ğ•šğ•Ÿ ğ•¥ğ•™ğ•– ğ•ğ•’ğ•¤ğ•¥ğ•–ğ•£ ğ•“ğ•£ğ•’ğ•Ÿğ•”ğ•™ ğŸ¥³ \n ğ•€ğ•¥ğ•¤ ğ•Ÿğ•’ğ•ğ•– ğ•šğ•¤ ${{ github.event.commits[0].message }} ğŸ˜± \n â„‚ğ•™ğ•–ğ•”ğ•œ ğ•šğ•¥ ğ• ğ•¦ğ•¥ ğ•™ğ•–ğ•£ğ•– ğŸ‘‡ \n ${{ github.event.commits[0].url }}"
            twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }} 
            twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }} 
            twitter_access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }} 
            twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} 

pull_request event

name: 'testing workflow'
# Trigger on pull_request
on: 
  pull_request:
    types:
      - opened
jobs:
  test:
    name: posting_on_twitter
    runs-on: ubuntu-latest
    steps:
      - name: tweety
        uses: m1ner79/Github-Twittction@{VERSION}
        with:
            twitter_status: "ğŸ…†ğŸ„´ ğŸ„²ğŸ„°ğŸ„½ ğŸ…‚ğŸ„´ğŸ„´ ğŸ„° ğŸ„¿ğŸ…„ğŸ„»ğŸ„»_ğŸ…ğŸ„´ğŸ…€ğŸ…„ğŸ„´ğŸ…‚ğŸ…ƒ ${{github.event.pull_request.title}} ğŸ„²ğŸ…ğŸ„´ğŸ„°ğŸ…ƒğŸ„´ğŸ„³ ğŸ„±ğŸ…ˆ ${{github.event.pull_request.head.repo.full_name}} ğŸ„²ğŸ„»ğŸ„¸ğŸ„²ğŸ„º ğŸ„·ğŸ„´ğŸ…ğŸ„´ ${{github.event.pull_request.html_url}} ğŸ„°ğŸ„½ğŸ„³ ğŸ…‚ğŸ„´ğŸ„´ ğŸ„¸ğŸ…ƒ ğŸ…ˆğŸ„¾ğŸ…„ğŸ…ğŸ…‚ğŸ„´ğŸ„»ğŸ„µ"
            twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }} 
            twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }} 
            twitter_access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }} 
            twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} 

release event

name: 'testing workflow'
# Trigger on release
on: 
  release:
    types: 
      - published
jobs:
  test:
    name: posting_on_twitter
    runs-on: ubuntu-latest
    steps:
      - name: tweety
        uses: m1ner79/Github-Twittction@{VERSION}
        with:
            twitter_status: "â“â“â“â“šâ“¢ â“›â“˜â“šâ“” â“ â“â“”â“¦ â“¡â“”â“›â“”â“â“¢â“” ${{github.event.release.tag_name}} â“˜â“¢ â“˜â“ ${{github.event.repository.full_name}}â€¯.â“‚â“â“¡â“” â““â“”â“£â“â“˜â“›â“¢ â“â“¡â“” â“â“¥â“â“˜â“›â“â“‘â“›â“” â“—â“”â“¡â“” ${{github.event.release.html_url}}"
            twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }} 
            twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }} 
            twitter_access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }} 
            twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} 

Without custom message

name: 'testing workflow'
# Trigger on push
on: 
  push:
    branches:
      - master
jobs:
  test:
    name: posting_on_twitter
    runs-on: ubuntu-latest
    steps:
      - name: tweety
        uses: m1ner79/Github-Twittction@{VERSION}
        with:
            # twitter_status: is deactivated so you will see one of our default messages
            # twitter_status: "â„ğ•–ğ•ª ğ•ªğ• ğ•¦! ğŸ‘‹ ğ•ğ•– ${{ github.event.repository.owner.name}} ğ•™ğ•’ğ•§ğ•– ğ•’ ğ•Ÿğ•–ğ•¨ ğ•”ğ• ğ•ğ•ğ•šğ•¥ ğ•šğ•Ÿ ğ•¥ğ•™ğ•– ğ•ğ•’ğ•¤ğ•¥ğ•–ğ•£ ğ•“ğ•£ğ•’ğ•Ÿğ•”ğ•™ ğŸ¥³ \n ğ•€ğ•¥ğ•¤ ğ•Ÿğ•’ğ•ğ•– ğ•šğ•¤ ${{ github.event.commits[0].message }} ğŸ˜± \n â„‚ğ•™ğ•–ğ•”ğ•œ ğ•šğ•¥ ğ• ğ•¦ğ•¥ ğ•™ğ•–ğ•£ğ•– ğŸ‘‡ \n ${{ github.event.commits[0].url }}"
            twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }} 
            twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }} 
            twitter_access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }} 
            twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} 

Default messages

push default message:
`${payload.pusher.name} just created a commit to ${payload.repository.full_name}. More details are available here: ${payload.commits[0].url}`

pull_request default message:
`${payload.pull_request.head.repo.full_name} just created a pull request: ${payload.pull_request.title}. More info is available here: ${payload.pull_request.html_url}`;

release default message:
`A new release ${payload.release.tag_name} is in ${payload.repository.full_name}. More details are available here ${payload.release.html_url}`;

Custom message

To create a custom twitter post I used these two websites:

    https://lingojam.com/TwitterFonts
    https://www.piliapp.com/twitter-symbols/

Go nuts and make it as sparkly as you like (just remember about twitter character limitations https://developer.twitter.com/en/docs/basics/counting-characters).
Contributing

Contributions are more than welcome handshake.
License

MIT
Stars
Contributors
@m1ner79 @dependabot
Categories
Chat Publishing
Links
m1ner79/Github-Twittction
Open issues 0
Pull requests 2
Report abuse

GitHub Twittction is not certified by GitHub. It is provided by a third-party and is governed by separate terms of service, privacy policy, and support documentation.
